// Code generated by "stringer -linecomment -type=RecordKind -output payload_enumstring.go"; DO NOT EDIT.

package stone1

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Meta-1]
	_ = x[Content-2]
	_ = x[Layout-3]
	_ = x[Index-4]
	_ = x[Attributes-5]
}

const _RecordKind_name = "MetaContentLayoutIndexAttributes"

var _RecordKind_index = [...]uint8{0, 4, 11, 17, 22, 32}

func (i RecordKind) String() string {
	i -= 1
	if i >= RecordKind(len(_RecordKind_index)-1) {
		return "RecordKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RecordKind_name[_RecordKind_index[i]:_RecordKind_index[i+1]]
}
