// Code generated by "stringer -type RecordType,RecordTag,Kind,Compression,Dependency"; DO NOT EDIT.

package payload

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RecordTypeUnknown-0]
	_ = x[RecordTypeInt8-1]
	_ = x[RecordTypeUint8-2]
	_ = x[RecordTypeInt16-3]
	_ = x[RecordTypeUint16-4]
	_ = x[RecordTypeInt32-5]
	_ = x[RecordTypeUint32-6]
	_ = x[RecordTypeInt64-7]
	_ = x[RecordTypeUint64-8]
	_ = x[RecordTypeString-9]
	_ = x[RecordTypeDependency-10]
	_ = x[RecordTypeProvider-11]
}

const _RecordType_name = "RecordTypeUnknownRecordTypeInt8RecordTypeUint8RecordTypeInt16RecordTypeUint16RecordTypeInt32RecordTypeUint32RecordTypeInt64RecordTypeUint64RecordTypeStringRecordTypeDependencyRecordTypeProvider"

var _RecordType_index = [...]uint8{0, 17, 31, 46, 61, 77, 92, 108, 123, 139, 155, 175, 193}

func (i RecordType) String() string {
	if i >= RecordType(len(_RecordType_index)-1) {
		return "RecordType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RecordType_name[_RecordType_index[i]:_RecordType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RecordTagName-1]
	_ = x[RecordTagArchitecture-2]
	_ = x[RecordTagVersion-3]
	_ = x[RecordTagSummary-4]
	_ = x[RecordTagDescription-5]
	_ = x[RecordTagHomepage-6]
	_ = x[RecordTagSourceID-7]
	_ = x[RecordTagDepends-8]
	_ = x[RecordTagProvides-9]
	_ = x[RecordTagConflicts-10]
	_ = x[RecordTagRelease-11]
	_ = x[RecordTagLicense-12]
	_ = x[RecordTagBuildRelease-13]
	_ = x[RecordTagPackageURI-14]
	_ = x[RecordTagPackageHash-15]
	_ = x[RecordTagPackageSize-16]
	_ = x[RecordTagBuildDepends-17]
	_ = x[RecordTagSourceURI-18]
	_ = x[RecordTagSourcePath-19]
	_ = x[RecordTagSourceRef-20]
}

const _RecordTag_name = "RecordTagNameRecordTagArchitectureRecordTagVersionRecordTagSummaryRecordTagDescriptionRecordTagHomepageRecordTagSourceIDRecordTagDependsRecordTagProvidesRecordTagConflictsRecordTagReleaseRecordTagLicenseRecordTagBuildReleaseRecordTagPackageURIRecordTagPackageHashRecordTagPackageSizeRecordTagBuildDependsRecordTagSourceURIRecordTagSourcePathRecordTagSourceRef"

var _RecordTag_index = [...]uint16{0, 13, 34, 50, 66, 86, 103, 120, 136, 153, 171, 187, 203, 224, 243, 263, 283, 304, 322, 341, 359}

func (i RecordTag) String() string {
	i -= 1
	if i >= RecordTag(len(_RecordTag_index)-1) {
		return "RecordTag(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RecordTag_name[_RecordTag_index[i]:_RecordTag_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindMeta-1]
	_ = x[KindContent-2]
	_ = x[KindLayout-3]
	_ = x[KindIndex-4]
	_ = x[KindAttributes-5]
	_ = x[KindDumb-6]
}

const _Kind_name = "KindMetaKindContentKindLayoutKindIndexKindAttributesKindDumb"

var _Kind_index = [...]uint8{0, 8, 19, 29, 38, 52, 60}

func (i Kind) String() string {
	i -= 1
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-1]
	_ = x[Zstd-2]
}

const _Compression_name = "NoneZstd"

var _Compression_index = [...]uint8{0, 4, 8}

func (i Compression) String() string {
	i -= 1
	if i >= Compression(len(_Compression_index)-1) {
		return "Compression(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Compression_name[_Compression_index[i]:_Compression_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DependencyPackageName-0]
	_ = x[DependencySharedLibrary-1]
	_ = x[DependencyPkgConfig-2]
	_ = x[DependencyInterpreter-3]
	_ = x[DependencyCMake-4]
	_ = x[DependencyPython-5]
	_ = x[DependencyBinary-6]
	_ = x[DependencySystemBinary-7]
	_ = x[DependencyPkgConfig32-8]
}

const _Dependency_name = "DependencyPackageNameDependencySharedLibraryDependencyPkgConfigDependencyInterpreterDependencyCMakeDependencyPythonDependencyBinaryDependencySystemBinaryDependencyPkgConfig32"

var _Dependency_index = [...]uint8{0, 21, 44, 63, 84, 99, 115, 131, 153, 174}

func (i Dependency) String() string {
	if i >= Dependency(len(_Dependency_index)-1) {
		return "Dependency(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Dependency_name[_Dependency_index[i]:_Dependency_index[i+1]]
}
